/*********************************************************************
** Program name: Lab 1
** Author: Jordan Hamilton
** Date: 04/08/2018
** Description: This program prompts the user to select a size
** (2x2 or 3x3) from a menu, then dynamically allocates a 2D array of
** the selected size that represents a matrix. A pointer to the array
** and the array's size are passed to the readMatrix function to fill
** the array with integer values. The pointer and size are passed
** again the determinant function to calculate the determinant.
** A visual representation of the matrix as well as the calculated
** determinant are displayed to the user.
*********************************************************************/

#include <cctype>
#include <iomanip>
#include <iostream>
#include <string>

#include "determinant.hpp"
#include "readMatrix.hpp"

using std::cin;
using std::cout;
using std::endl;
using std::setw;
using std::string;


bool validateInput(string inputStr);

/***********************************************************************************************
** Description: This program can be run via the lab1 executable generated by make.
***********************************************************************************************/
int main() {
  string matrixSize;


  do {
    cout << "Select a valid matrix size to calculate the determinant:" << endl;
    cout << "1) 2x2" << endl;
    cout << "2) 3x3" << endl;
    getline(cin, matrixSize);
  } while(!validateInput(matrixSize));
}

bool validateInput(string inputStr) {
  bool isValid = true;

  for (int i = 0; i < inputStr.length(); i++) {
    if (!isdigit(inputStr[i])) {
      isValid = false;
    }
  }

  return isValid;
}
